---
title: "The Impact of Gender on Canadian Unemployment "
subtitle: "2018 to 2023"
author: 
  - Fatimah Yunusa
thanks: "Code and data are available at: https://github.com/fatimahsy/Gender-Unemployment-.git."
date: today
date-format: long
abstract: "This paper examines the impact of gender on unemployment rates across various demographics from 2018 to 2023, employing a comprehensive dataset from the Labor Force Survey to unravel the interplay between gender and overall economic participation.We also imploy the use of a linear regression model to help disect the influence of gender, among other predictors, on the unemployment rates of Generatinon Z. Our findings reveal significant disparities in unemployment trends, with distinct patterns emerging between different genders and age groups, hilighting the persistent gender gap in the labour market. This reaserch is important because it shows the underlying factors that contribute to unemployment disparities, offering insights into the effectiveness of current policies and the need for targeted interventions.Ultimately, this paper enhances our understanding of the labour market's complexities, advocating for inclusinve economic strategies to bridge the gender divide in employment opportunities. "
format: pdf
number-sections: true
bibliography: references.bib
toc: true 
---

```{r}
#| include: false
#| warning: false
#| message: false

library(readr)
library(lubridate)
library(tidyverse)
library(dplyr)
library(tidyr)
library(knitr)
library(janitor)
library(scales)
library(RColorBrewer)
library(ggplot2)
library(kableExtra)
library(here)
library(arrow)
library(rstanarm)
library(modelsummary)
```

# Introduction

In todays rapidly changing economy, understanding the dynamics of unemployment through the perspective of gender provides crucial insights into the structural inequalities that exist in the labour market. There has always been a persistent gender gap in unemployment rates as a result of normalised gender roles in society. However, in the recent decade, their is an increasing decrease in the size of the gender gap. This can largely be attributed to increased educational attainment among women, changing gender norms, increased childcare support and flexibility, economic shift from manufacturing to service sector, and corporate inclusion efforts. Globally, finding a job as a woman is much harder and when women finally get jobs, they statistically work in low quality jobs (@citesource1). 

By examining the interplay between gender and unemployment rates, this paper aims to uncover the underlying patterns that continue to disadvantage one gender over another, in order to offer more efficient and equitable economic policies that decrease the unemployment gap. A Addressing this gap not only positively contributes to economic theory but also has practical implications for improving workforce inclusivity and economic resilience.

This paper leverages a very comprehensive dataset derived from the `Labour Force Survey` [@citedatasetsource] spanning from 2018 to 2023, a period that is notable for its socio-economic turbulence and technological disruptions because of Covid-19 and the increase in artificial intelligence.

Current research in this area has an extensive gap that needs to be filled because despite extensive research in the area, the interplay between gender, age, and unemployment within the specific context of Generation Z remains inadequately explored. 

To address this gap, we employ the use of a linear regression model to scrutinize the influence of gender alongside other predictors of unemployment rates. The estimand in our study is the differential impact of gender on the likelihood of unemployment for individuals within the Generation Z demographic, holding other variables constant. 

Our statistical analysis shows that employment trends exhibit significant disparities. These findings affirm the existence of a gender gap but also highlight its persistence and complexity within the labour force. 

There are many implications of this research.Understanding the underlying factors of the gender gap in unemployment allows us to evaluate the effectiveness of current Canadian labour force policies. Ultimately, this paper contributes to  discussions about labour economics in Canada by advocating for more inclusive policies that aim at decreasing the unemployment gap. 

The paper is structured as follows: Following this introduction, we describe the methodology and data sources used in the analysis in (@sec-data). (@sec-model)describes the model utilized in this paper, and results (@sec-results) relays the results of our statistical analysis. The paper concludes with a discussion (@sec-discussion) of the implications of the results, possible causes, weaknesses and next steps.

# Data {#sec-data}

## Data source

## Datat Features

## Data Analysis

To carry out statistical analysis, this paper uses the Statistics of Canada `Labour force characteristics by sex and detailed age group, annual` [@citedataset] dataset. We are using the `R programming language` [@citeR] to conduct the analysis along with `readR` [@citereadR], `lubridate` [@citelubridate], `tidyverse` [@citetidyverse], `dplyr` [@citedplyr], `tidyr` [@citetidyr], `knitr` [@citeknitr], `janitor` [@citejanitor], `scales` [@citescales], `RColorBrewer` [@citeRColorBrewer], `ggplot2` [@citeggplot2], `kableExtra` [@citekableExtra], `here` [@citeHere], `arrow` [@citeArrow], `rstanarm` [@citerstanarm], `modelsummary` [@citemodelsummary], and `lme4` [@citelme4].

# Model {#sec-model}

## Model Set-up

$$
\begin{aligned}
\text{Gen Z Unemployment} = \beta_0 &+ \beta_1 \cdot \text{Sex} \\
&+ \beta_2 \cdot \text{Reference Period} \\
&+ \beta_3 \cdot \text{Adult Unemployment} \\
&+ \beta_4 \cdot \text{Seniors Unemployment} + \epsilon
\end{aligned}
$$

Where:

-   `Gen z Unemployment` is
-   `Sex` is
-   `Reference Period` is another independent variable that represents the time frame of the data collection (e.g., year).
-   `Adult Unemployment` and `Seniors Unemployment` are independent variables
-   $\beta_0$ is the y-intercept, representing the expected value of `Gen z Unemployment` when all the independent variables are 0.
-   $\beta_1, \beta_2, \beta_3, \beta_4$ are the coefficients for each independent variable, representing the change in `Gen z Unemployment` for a one-unit change in the respective independent variable, holding all other variables constant.
-   $\epsilon$ represents the error term, accounting for the variability in `Gen z Unemployment` not explained by the model.

Talk more about it.

## Model Justification

# Results {#sec-results}

## Generation Z unemployment

## Seniors Unemployment

## Adults Unemployment

# Discussion {#sec-discussion}

## Implications of these results

## Possible Causes

## Weaknesses and next steps

# Conclusion

\newpage

\appendix

# Appendix {.unnumbered}

# Additional data detail

\newpage

# References
